import json

# Define the complete League of Legends dataset for Patch 16.16.1

ITEMS = {
    # Starters & Consumables
    "1054": {"id": "1054", "name": "Doran's Shield", "gold": 450, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1054.png", "desc": "+110 Health, Health Regen, Endure passive."},
    "1055": {"id": "1055", "name": "Doran's Blade", "gold": 450, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1055.png", "desc": "+10 AD, +100 Health, +3.5% Lifesteal."},
    "1056": {"id": "1056", "name": "Doran's Ring", "gold": 400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1056.png", "desc": "+18 AP, +90 Health, Mana Regen passive."},
    "1082": {"id": "1082", "name": "Dark Seal", "gold": 350, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1082.png", "desc": "+15 AP, +40 Health. Grants AP on champion kills/assists."},
    "1083": {"id": "1083", "name": "Cull", "gold": 450, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1083.png", "desc": "+7 AD, +3 Life on hit. Grants bonus gold after 100 CS."},
    "2003": {"id": "2003", "name": "Health Potion", "gold": 50, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/2003.png", "desc": "Restores 120 Health over 15 seconds."},
    "2031": {"id": "2031", "name": "Refillable Potion", "gold": 150, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/2031.png", "desc": "Holds 2 charges that restore 100 Health each."},
    "1101": {"id": "1101", "name": "Mosstomper Seedling", "gold": 450, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1101.png", "desc": "Jungle starter item. Grants Tenacity and Shield upon fully grown."},
    "1102": {"id": "1102", "name": "Scorchclaw Pup", "gold": 450, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1102.png", "desc": "Jungle starter item. Grants slow and bonus damage upon fully grown."},
    "1103": {"id": "1103", "name": "Gustwalker Hatchling", "gold": 450, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1103.png", "desc": "Jungle starter item. Grants bonus Movement Speed upon fully grown."},
    "3865": {"id": "3865", "name": "World Atlas", "gold": 400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3865.png", "desc": "Support starter item. Generates gold from hitting enemies or executing minions."},
    "3869": {"id": "3869", "name": "Celestial Opposition", "gold": 400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3869.png", "desc": "Support upgrade. Grants damage reduction when taking champion damage."},
    "3870": {"id": "3870", "name": "Dream Maker", "gold": 400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3870.png", "desc": "Support upgrade. Buffs ally shields/heals with damage reduction & bonus damage."},
    "3871": {"id": "3871", "name": "Solstice Sleigh", "gold": 400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3871.png", "desc": "Support upgrade. Slowing or immobilizing an enemy grants Move Speed & Health."},
    "3876": {"id": "3876", "name": "Bloodsong", "gold": 400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3876.png", "desc": "Support upgrade. Spellblade: empowers next basic attack and exposes target for 10% more damage."},
    "3877": {"id": "3877", "name": "Zaz'Zak's Realmspike", "gold": 400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3877.png", "desc": "Support upgrade. Damaging champions causes an explosion dealing % max health damage."},

    # Basic Components
    "1001": {"id": "1001", "name": "Boots", "gold": 300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1001.png", "desc": "+25 Movement Speed."},
    "1011": {"id": "1011", "name": "Giant's Belt", "gold": 900, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1011.png", "desc": "+350 Health."},
    "1026": {"id": "1026", "name": "Blasting Wand", "gold": 850, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1026.png", "desc": "+40 Ability Power."},
    "1028": {"id": "1028", "name": "Ruby Crystal", "gold": 400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1028.png", "desc": "+150 Health."},
    "1029": {"id": "1029", "name": "Cloth Armor", "gold": 300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1029.png", "desc": "+15 Armor."},
    "1031": {"id": "1031", "name": "Chain Vest", "gold": 800, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1031.png", "desc": "+40 Armor."},
    "1033": {"id": "1033", "name": "Null-Magic Mantle", "gold": 400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1033.png", "desc": "+20 Magic Resist."},
    "1036": {"id": "1036", "name": "Long Sword", "gold": 350, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1036.png", "desc": "+10 Attack Damage."},
    "1037": {"id": "1037", "name": "Pickaxe", "gold": 875, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1037.png", "desc": "+25 Attack Damage."},
    "1038": {"id": "1038", "name": "B. F. Sword", "gold": 1300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1038.png", "desc": "+40 Attack Damage."},
    "1042": {"id": "1042", "name": "Dagger", "gold": 250, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1042.png", "desc": "+10% Attack Speed."},
    "1043": {"id": "1043", "name": "Recurve Bow", "gold": 700, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1043.png", "desc": "+15% Attack Speed, on-hit magic damage."},
    "1052": {"id": "1052", "name": "Amplifying Tome", "gold": 400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1052.png", "desc": "+20 Ability Power."},
    "1053": {"id": "1053", "name": "Vampiric Scepter", "gold": 900, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1053.png", "desc": "+15 AD, +7% Lifesteal."},
    "1058": {"id": "1058", "name": "Needlessly Large Rod", "gold": 1200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/1058.png", "desc": "+65 Ability Power."},
    "2021": {"id": "2021", "name": "Tunneler", "gold": 1150, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/2021.png", "desc": "+15 AD, +250 Health."},
    "3044": {"id": "3044", "name": "Phage", "gold": 1100, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3044.png", "desc": "+15 AD, +200 Health. Basic attacks grant Movement Speed."},
    "3057": {"id": "3057", "name": "Sheen", "gold": 900, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3057.png", "desc": "+10 Ability Haste. Spellblade passive."},
    "3067": {"id": "3067", "name": "Kindlegem", "gold": 800, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3067.png", "desc": "+200 Health, +10 Ability Haste."},
    "3070": {"id": "3070", "name": "Tear of the Goddess", "gold": 400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3070.png", "desc": "+240 Mana. Charges mana upon hitting abilities."},
    "3123": {"id": "3123", "name": "Executioner's Calling", "gold": 800, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3123.png", "desc": "+15 AD. Grievous Wounds."},
    "3133": {"id": "3133", "name": "Caulfield's Warhammer", "gold": 1050, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3133.png", "desc": "+20 AD, +10 Ability Haste."},
    "3134": {"id": "3134", "name": "Serrated Dirk", "gold": 1000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3134.png", "desc": "+20 AD, +10 Lethality."},
    "3145": {"id": "3145", "name": "Hextech Alternator", "gold": 1100, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3145.png", "desc": "+45 AP. Revved passive magic damage."},
    "3191": {"id": "3191", "name": "Seeker's Armguard", "gold": 1600, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3191.png", "desc": "+40 AP, +35 Armor. Stasis active."},

    # Boots
    "3006": {"id": "3006", "name": "Berserker's Greaves", "gold": 1100, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3006.png", "desc": "+30% Attack Speed, +45 Movement Speed."},
    "3009": {"id": "3009", "name": "Boots of Swiftness", "gold": 1000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3009.png", "desc": "+60 Movement Speed, +25% Slow Resist."},
    "3020": {"id": "3020", "name": "Sorcerer's Shoes", "gold": 1100, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3020.png", "desc": "+18 Magic Penetration, +45 Movement Speed."},
    "3047": {"id": "3047", "name": "Plated Steelcaps", "gold": 1200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3047.png", "desc": "+20 Armor, +45 Movement Speed, -12% damage from basic attacks."},
    "3111": {"id": "3111", "name": "Mercury's Treads", "gold": 1200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3111.png", "desc": "+25 Magic Resist, +45 Movement Speed, +30% Tenacity."},
    "3158": {"id": "3158", "name": "Ionian Boots of Lucidity", "gold": 900, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3158.png", "desc": "+15 Ability Haste, +12 Summoner Spell Haste, +45 Movement Speed."},
    "3042": {"id": "3042", "name": "Symbiotic Soles", "gold": 900, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3042.png", "desc": "+35 Movement Speed. Empowers Recall."},

    # Fighter & Bruiser
    "3071": {"id": "3071", "name": "Black Cleaver", "gold": 3000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3071.png", "desc": "+55 AD, +400 Health, +20 Ability Haste. Carves enemy armor up to 30%."},
    "3074": {"id": "3074", "name": "Ravenous Hydra", "gold": 3300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3074.png", "desc": "+70 AD, +20 Ability Haste, +12% Lifesteal. Cleave active & passive."},
    "3078": {"id": "3078", "name": "Trinity Force", "gold": 3333, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3078.png", "desc": "+36 AD, +33% AS, +300 Health, +15 Ability Haste. Spellblade + Quicken."},
    "3153": {"id": "3153", "name": "Blade of the Ruined King", "gold": 3200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3153.png", "desc": "+40 AD, +25% AS, +10% Lifesteal. On-hit % Current Health damage."},
    "3156": {"id": "3156", "name": "Maw of Malmortius", "gold": 3100, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3156.png", "desc": "+70 AD, +40 MR, +15 Ability Haste. Lifeline magic shield."},
    "3161": {"id": "3161", "name": "Spear of Shojin", "gold": 3100, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3161.png", "desc": "+55 AD, +300 Health, +20 Basic Ability Haste. Increases spell damage up to 12%."},
    "3181": {"id": "3181", "name": "Hullbreaker", "gold": 3000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3181.png", "desc": "+65 AD, +350 Health, +5% Movement Speed. Empowers siege and attacks against structures."},
    "3748": {"id": "3748", "name": "Titanic Hydra", "gold": 3300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3748.png", "desc": "+50 AD, +550 Health. Cleave active resets attack timer and deals cone damage."},
    "6333": {"id": "6333", "name": "Death's Dance", "gold": 3300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6333.png", "desc": "+60 AD, +40 Armor, +15 Ability Haste. Stores 30% damage taken as bleed, cleanses on takedown."},
    "6610": {"id": "6610", "name": "Sundered Sky", "gold": 3100, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6610.png", "desc": "+55 AD, +450 Health, +15 Ability Haste. Lightshield Strike critically strikes and heals for missing HP."},
    "6631": {"id": "6631", "name": "Stridebreaker", "gold": 3300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6631.png", "desc": "+50 AD, +30% AS, +400 Health. Halting Slash active slows nearby enemies and speeds up champion."},
    "6692": {"id": "6692", "name": "Eclipse", "gold": 2800, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6692.png", "desc": "+70 AD, +15 Ability Haste. Ever Rising Moon shields on 2 separate attacks/spells."},
    "3053": {"id": "3053", "name": "Sterak's Gage", "gold": 3200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3053.png", "desc": "+400 Health. Grants bonus AD equal to 50% base AD and Lifeline shield + Tenacity."},
    "2503": {"id": "2503", "name": "Overlord's Bloodmail", "gold": 3300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/2503.png", "desc": "+550 Health, +40 AD. Tyranny: Grants bonus AD equal to 2% bonus Health."},

    # Tanks
    "3068": {"id": "3068", "name": "Sunfire Aegis", "gold": 2700, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3068.png", "desc": "+500 Health, +50 Armor. Immolate aura deals scaling magic damage."},
    "3075": {"id": "3075", "name": "Thornmail", "gold": 2700, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3075.png", "desc": "+350 Health, +70 Armor. Reflects magic damage and inflicts Grievous Wounds."},
    "3083": {"id": "3083", "name": "Warmog's Armor", "gold": 3100, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3083.png", "desc": "+1000 Health, +100% Base Health Regen. Warmog's Heart rapid regen out of combat."},
    "3084": {"id": "3084", "name": "Heartsteel", "gold": 3000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3084.png", "desc": "+900 Health, +200% Base Health Regen. Colossal Consumption permanently stacks maximum Health."},
    "3110": {"id": "3110", "name": "Frozen Heart", "gold": 2500, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3110.png", "desc": "+65 Armor, +400 Mana, +20 Ability Haste. Reduces nearby enemies' Attack Speed by 20%."},
    "3143": {"id": "3143", "name": "Randuin's Omen", "gold": 2700, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3143.png", "desc": "+400 Health, +60 Armor. Reduces incoming critical damage by 30% and active slow."},
    "3065": {"id": "3065", "name": "Spirit Visage", "gold": 2900, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3065.png", "desc": "+450 Health, +50 MR, +10 Ability Haste. Increases all healing and shielding received by 25%."},
    "4401": {"id": "4401", "name": "Force of Nature", "gold": 2800, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/4401.png", "desc": "+400 Health, +55 MR, +5% Move Speed. Taking magic damage grants stacking MR & Move Speed."},
    "2504": {"id": "2504", "name": "Kaenic Rookern", "gold": 2900, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/2504.png", "desc": "+400 Health, +80 MR, +150% Health Regen. Grants a 18% max health magic shield when out of combat."},
    "6664": {"id": "6664", "name": "Hollow Radiance", "gold": 2800, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6664.png", "desc": "+600 Health, +40 MR, +10 Ability Haste. Immolate + Desolation minion waveclear explosion."},
    "6665": {"id": "6665", "name": "Jak'Sho, The Protean", "gold": 3200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6665.png", "desc": "+300 Health, +50 Armor, +50 MR. In combat, increases bonus Armor and MR by 30%."},
    "6662": {"id": "6662", "name": "Iceborn Gauntlet", "gold": 2600, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6662.png", "desc": "+300 Health, +50 Armor, +15 Ability Haste. Spellblade creates a slowing frost field."},
    "3742": {"id": "3742", "name": "Dead Man's Plate", "gold": 2900, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3742.png", "desc": "+550 Health, +45 Armor, +5% Move Speed. Shipwrecker builds Momentum for empowered melee attacks."},

    # Mages & AP
    "3003": {"id": "3003", "name": "Archangel's Staff", "gold": 2900, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3003.png", "desc": "+80 AP, +860 Mana, +25 Ability Haste. Transforms into Seraph's Embrace for a massive Lifeline shield."},
    "3089": {"id": "3089", "name": "Rabadon's Deathcap", "gold": 3600, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3089.png", "desc": "+140 Ability Power. Increases total Ability Power by 35%."},
    "3100": {"id": "3100", "name": "Lich Bane", "gold": 3100, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3100.png", "desc": "+100 AP, +15 Ability Haste, +8% Move Speed. Spellblade delivers devastating burst on basic attacks."},
    "3115": {"id": "3115", "name": "Nashor's Tooth", "gold": 3000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3115.png", "desc": "+90 AP, +50% Attack Speed, +15 Ability Haste. On-hit magic damage scaling with AP."},
    "3116": {"id": "3116", "name": "Rylai's Crystal Scepter", "gold": 2600, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3116.png", "desc": "+75 AP, +400 Health. Damaging spells slow targets by 30% for 1 second."},
    "3118": {"id": "3118", "name": "Malignance", "gold": 2700, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3118.png", "desc": "+80 AP, +600 Mana, +25 Ultimate Haste. Ultimates create a pool shredding MR and dealing magic burn."},
    "3135": {"id": "3135", "name": "Void Staff", "gold": 3000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3135.png", "desc": "+80 AP, +40% Magic Penetration."},
    "3137": {"id": "3137", "name": "Cryptbloom", "gold": 2850, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3137.png", "desc": "+70 AP, +15 Ability Haste, +30% Magic Penetration. Takedowns spawn a healing wave for allies."},
    "3151": {"id": "3151", "name": "Liandry's Torment", "gold": 3000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3151.png", "desc": "+90 AP, +300 Health. Torment burns for 2% max HP per second and ramps up total damage by 6%."},
    "3157": {"id": "3157", "name": "Zhonya's Hourglass", "gold": 3250, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3157.png", "desc": "+120 AP, +50 Armor. Stasis active makes you invulnerable and untargetable for 2.5s."},
    "4628": {"id": "4628", "name": "Horizon Focus", "gold": 2700, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/4628.png", "desc": "+90 AP, +20 Ability Haste. Reveals and increases damage dealt to enemies hit at long range by 10%."},
    "4629": {"id": "4629", "name": "Cosmic Drive", "gold": 3000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/4629.png", "desc": "+70 AP, +350 Health, +25 Ability Haste, +5% Move Speed. Spells grant ramping Movement Speed."},
    "4633": {"id": "4633", "name": "Riftmaker", "gold": 3100, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/4633.png", "desc": "+80 AP, +350 Health, +15 Ability Haste. In combat, deals up to 10% bonus damage and grants Omnivamp."},
    "4645": {"id": "4645", "name": "Shadowflame", "gold": 3200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/4645.png", "desc": "+110 AP, +12 Magic Pen. Magic & True damage critically strike targets below 35% health for +20% damage."},
    "6655": {"id": "6655", "name": "Luden's Companion", "gold": 2900, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6655.png", "desc": "+90 AP, +600 Mana, +20 Ability Haste. Fires loaded Shot charges to deal burst AOE magic damage."},
    "6657": {"id": "6657", "name": "Rod of Ages", "gold": 2600, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6657.png", "desc": "+50 AP, +400 Health, +400 Mana. Gains stats every minute and grants a free level upon 10 stacks."},
    "2508": {"id": "2508", "name": "Stormsurge", "gold": 2900, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/2508.png", "desc": "+95 AP, +10 Magic Pen, +5% Move Speed. Squall strikes high burst damage and yields bonus gold."},

    # Marksman / ADC
    "3031": {"id": "3031", "name": "Infinity Edge", "gold": 3400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3031.png", "desc": "+80 AD, +25% Crit. Increases Critical Strike Damage by 40%."},
    "3032": {"id": "3032", "name": "Yun Tal Wildarrows", "gold": 3200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3032.png", "desc": "+65 AD, +25% Crit. Critical strikes apply a stacking physical bleed."},
    "3033": {"id": "3033", "name": "Mortal Reminder", "gold": 3000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3033.png", "desc": "+35 AD, +25% Crit, +35% Armor Pen. Physical damage applies Grievous Wounds."},
    "3036": {"id": "3036", "name": "Lord Dominik's Regards", "gold": 3000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3036.png", "desc": "+45 AD, +25% Crit, +40% Armor Penetration."},
    "3046": {"id": "3046", "name": "Phantom Dancer", "gold": 2600, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3046.png", "desc": "+60% Attack Speed, +25% Crit, +12% Move Speed. Ghosting passive."},
    "3072": {"id": "3072", "name": "Bloodthirster", "gold": 3400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3072.png", "desc": "+80 AD, +18% Lifesteal. Ichorshield converts excess healing into a protective shield."},
    "3085": {"id": "3085", "name": "Runaan's Hurricane", "gold": 2600, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3085.png", "desc": "+40% Attack Speed, +25% Crit, +7% Move Speed. Wind's Fury fires bolts at 2 extra enemies."},
    "3087": {"id": "3087", "name": "Statikk Shiv", "gold": 2900, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3087.png", "desc": "+50 AD, +35% Attack Speed, +4% Move Speed. Takedowns or basic attacks unleash chain lightning."},
    "3094": {"id": "3094", "name": "Rapid Firecannon", "gold": 2600, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3094.png", "desc": "+35% Attack Speed, +25% Crit, +7% Move Speed. Energized attack gains +35% attack range."},
    "3302": {"id": "3302", "name": "Terminus", "gold": 3000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3302.png", "desc": "+35 AD, +35% AS. Alternates between Light (Armor/MR shred) and Dark (bonus Armor/MR) on-hit."},
    "3508": {"id": "3508", "name": "Essence Reaver", "gold": 3150, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3508.png", "desc": "+65 AD, +25% Crit, +15 Ability Haste. Basic attacks restore mana."},
    "6672": {"id": "6672", "name": "Kraken Slayer", "gold": 3100, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6672.png", "desc": "+50 AD, +40% AS, +7% Move Speed. Bring It Down deals ramping bonus physical damage every 3rd attack."},
    "6673": {"id": "6673", "name": "Immortal Shieldbow", "gold": 3000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6673.png", "desc": "+55 AD, +25% Crit. Lifeline grants a massive shield when dropped below 30% health."},
    "6675": {"id": "6675", "name": "Navori Flickerblade", "gold": 2600, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6675.png", "desc": "+40% Attack Speed, +25% Crit, +7% Move Speed. Basic attacks reduce non-ultimate cooldowns by 15%."},
    "6676": {"id": "6676", "name": "The Collector", "gold": 3100, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6676.png", "desc": "+60 AD, +25% Crit, +12 Lethality. Death and Taxes executes enemies below 5% health and gives +25g."},
    "3026": {"id": "3026", "name": "Guardian Angel", "gold": 3200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3026.png", "desc": "+55 AD, +45 Armor. Resurrects champion with 50% base health upon lethal damage."},

    # Assassins & Lethality
    "3142": {"id": "3142", "name": "Youmuu's Ghostblade", "gold": 2700, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3142.png", "desc": "+60 AD, +18 Lethality. Active Wraith Step grants +25% Move Speed and ghosting."},
    "3179": {"id": "3179", "name": "Umbral Glaive", "gold": 2500, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3179.png", "desc": "+50 AD, +15 Lethality, +15 Ability Haste. Blackout reveals and insta-kills stealth wards & traps."},
    "3814": {"id": "3814", "name": "Edge of Night", "gold": 2800, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3814.png", "desc": "+50 AD, +15 Lethality, +250 Health. Spell Shield blocks the next hostile ability."},
    "5803": {"id": "5803", "name": "Serpent's Fang", "gold": 2500, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/5803.png", "desc": "+55 AD, +15 Lethality. Shield Reaver reduces enemy shields by 50%."},
    "6694": {"id": "6694", "name": "Serylda's Grudge", "gold": 3200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6694.png", "desc": "+45 AD, +15 Lethality, +30% Armor Pen, +15 Ability Haste. Spells slow low HP enemies."},
    "6696": {"id": "6696", "name": "Axiom Arc", "gold": 3000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6696.png", "desc": "+55 AD, +18 Lethality, +20 Ability Haste. Takedowns refund 25% total Ultimate Cooldown."},
    "6697": {"id": "6697", "name": "Voltaic Cyclosword", "gold": 2900, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6697.png", "desc": "+55 AD, +18 Lethality, +15 Ability Haste. Energized attacks slow targets by 99% for 0.75s."},
    "6698": {"id": "6698", "name": "Hubris", "gold": 3000, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6698.png", "desc": "+60 AD, +18 Lethality, +15 Ability Haste. Takedowns summon a statue and grant ramping bonus AD."},
    "6699": {"id": "6699", "name": "Profane Hydra", "gold": 3300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6699.png", "desc": "+60 AD, +18 Lethality, +20 Ability Haste. Heretical Cleave executes low health targets."},
    "6701": {"id": "6701", "name": "Opportunity", "gold": 2700, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6701.png", "desc": "+55 AD, +18 Lethality, +5% Move Speed. Preparation gives +11 Lethality and speed on takedown."},

    # Supports & Enchanters
    "2065": {"id": "2065", "name": "Shurelya's Battlesong", "gold": 2200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/2065.png", "desc": "+55 AP, +15 Ability Haste, +4% Move Speed. Inspires nearby allies with +30% Move Speed."},
    "3107": {"id": "3107", "name": "Redemption", "gold": 2300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3107.png", "desc": "+200 Health, +15 Ability Haste, +15% Heal & Shield Power. Active heals all allies in area."},
    "3109": {"id": "3109", "name": "Knight's Vow", "gold": 2200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3109.png", "desc": "+200 Health, +40 Armor, +10 Ability Haste. Redirects 12% of damage taken by Worthy Ally to self."},
    "3190": {"id": "3190", "name": "Locket of the Iron Solari", "gold": 2200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3190.png", "desc": "+200 Health, +30 Armor, +30 MR. Active shields all nearby allies."},
    "3222": {"id": "3222", "name": "Mikael's Blessing", "gold": 2300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3222.png", "desc": "+250 Health, +15 Ability Haste, +15% Heal/Shield. Active cleanses all CC from an ally and heals."},
    "3504": {"id": "3504", "name": "Ardent Censer", "gold": 2300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3504.png", "desc": "+50 AP, +8% Heal/Shield, +4% Move Speed. Healing/shielding allies grants Attack Speed and on-hit magic damage."},
    "3744": {"id": "3744", "name": "Staff of Flowing Water", "gold": 2300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3744.png", "desc": "+40 AP, +8% Heal/Shield, +15 Ability Haste. Healing/shielding allies grants AP and Ability Haste."},
    "4005": {"id": "4005", "name": "Imperial Mandate", "gold": 2300, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/4005.png", "desc": "+55 AP, +20 Ability Haste, +4% Move Speed. Slows/immobilizes mark enemies for ally detonation."},
    "6617": {"id": "6617", "name": "Moonstone Renewer", "gold": 2700, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/6617.png", "desc": "+30 AP, +250 Health, +20 Ability Haste, +16% Heal/Shield. Chains heals and shields to nearby allies."},
    "2501": {"id": "2501", "name": "Trailblazer", "gold": 2400, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/2501.png", "desc": "+200 Health, +40 Armor, +5% Move Speed. Lead the Way speeds up following allies and slows on attack."},
    "3050": {"id": "3050", "name": "Zeke's Convergence", "gold": 2200, "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/item/3050.png", "desc": "+300 Health, +30 Armor, +30 MR. Casting Ultimate surrounds you in an icy froststorm dealing damage & slowing."}
}

RUNES = {
    # Precision
    "8000": {"id": 8000, "name": "Precision", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/7201_Precision.png", "desc": "Become a Legend. Improved attacks and sustained damage."},
    "8005": {"id": 8005, "name": "Press the Attack", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/PressTheAttack/PressTheAttack.png", "desc": "Hitting an enemy champion with 3 consecutive basic attacks deals bonus damage and exposes them."},
    "8008": {"id": 8008, "name": "Lethal Tempo", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/LethalTempo/LethalTempoTemp.png", "desc": "Attacking an enemy champion grants stacking Attack Speed. At max stacks, basic attacks deal on-hit damage."},
    "8021": {"id": 8021, "name": "Fleet Footwork", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/FleetFootwork/FleetFootwork.png", "desc": "Attacking and moving builds Energy charges. At 100 charges, your next attack heals and grants Move Speed."},
    "8010": {"id": 8010, "name": "Conqueror", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/Conqueror/Conqueror.png", "desc": "Attacks and spells grant stacking Adaptive Force (up to 12 stacks). At max stacks, heals for 8% of damage dealt."},
    "9101": {"id": 9101, "name": "Absorb Life", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/AbsorbLife/AbsorbLife.png", "desc": "Killing a target heals you for 2-17 Health."},
    "9111": {"id": 9111, "name": "Triumph", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/Triumph.png", "desc": "Champion takedowns restore 5% missing health and grant 20 gold."},
    "8009": {"id": 8009, "name": "Presence of Mind", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/PresenceOfMind/PresenceOfMind.png", "desc": "Damaging an enemy champion increases your mana regen. Takedowns restore 15% max mana or energy."},
    "9104": {"id": 9104, "name": "Legend: Alacrity", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/LegendAlacrity/LegendAlacrity.png", "desc": "Gain 3% Attack Speed plus an additional 1.5% per Legend stack (max 10 stacks = 18% AS)."},
    "9105": {"id": 9105, "name": "Legend: Haste", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/LegendHaste/LegendHaste.png", "desc": "Gain 1.5 Basic Ability Haste per Legend stack (up to 15 Basic Ability Haste)."},
    "9103": {"id": 9103, "name": "Legend: Bloodline", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/LegendBloodline/LegendBloodline.png", "desc": "Gain 0.35% Lifesteal per Legend stack (max 5.25% Lifesteal) and 85 Max Health."},
    "8014": {"id": 8014, "name": "Coup de Grace", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/CoupDeGrace/CoupDeGrace.png", "desc": "Deal 8% more damage to champions below 40% health."},
    "8017": {"id": 8017, "name": "Cut Down", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Precision/CutDown/CutDown.png", "desc": "Deal 8% more damage to champions who have above 60% maximum health."},
    "8299": {"id": 8299, "name": "Last Stand", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/LastStand/LastStand.png", "desc": "Deal 5% to 11% more damage to champions while you are below 60% health."},

    # Domination
    "8100": {"id": 8100, "name": "Domination", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/7200_Domination.png", "desc": "Hunt and Eliminate Prey. Burst damage and target access."},
    "8112": {"id": 8112, "name": "Electrocute", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/Electrocute/Electrocute.png", "desc": "Hitting a champion with 3 separate attacks or abilities within 3s deals bonus adaptive burst damage."},
    "8128": {"id": 8128, "name": "Dark Harvest", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/DarkHarvest/DarkHarvest.png", "desc": "Damaging a champion below 50% health deals adaptive damage and soul-harvests their soul, stacking damage."},
    "9923": {"id": 9923, "name": "Hail of Blades", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/HailOfBlades/HailOfBlades.png", "desc": "Gain 110% Attack Speed for the first 3 basic attacks against enemy champions."},
    "8126": {"id": 8126, "name": "Cheap Shot", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/CheapShot/CheapShot.png", "desc": "Damaging champions with impaired movement or actions deals bonus true damage."},
    "8139": {"id": 8139, "name": "Taste of Blood", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/TasteOfBlood/GreenTerror_TasteOfBlood.png", "desc": "Heal when you damage an enemy champion."},
    "8143": {"id": 8143, "name": "Sudden Impact", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/SuddenImpact/SuddenImpact.png", "desc": "After using a dash, leap, blink, teleport or exiting stealth, deal bonus true damage."},
    "8136": {"id": 8136, "name": "Zombie Ward", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/ZombieWard/ZombieWard.png", "desc": "Takedowns on enemy wards spawn a friendly Zombie Ward and grant permanent Adaptive Force."},
    "8120": {"id": 8120, "name": "Ghost Poro", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/GhostPoro/GhostPoro.png", "desc": "When your wards expire, they leave behind a Ghost Poro granting vision and Adaptive Force."},
    "8138": {"id": 8138, "name": "Eyeball Collection", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/EyeballCollection/EyeballCollection.png", "desc": "Collect eyeballs for champion takedowns. Grants permanent Adaptive Force."},
    "8135": {"id": 8135, "name": "Treasure Hunter", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/TreasureHunter/TreasureHunter.png", "desc": "Gain bonus gold on unique champion takedowns (up to 450 bonus gold)."},
    "8105": {"id": 8105, "name": "Relentless Hunter", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/RelentlessHunter/RelentlessHunter.png", "desc": "Gain out-of-combat Movement Speed per unique takedown."},
    "8106": {"id": 8106, "name": "Ultimate Hunter", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Domination/UltimateHunter/UltimateHunter.png", "desc": "Your ultimate gains 6 Ability Haste plus 5 per unique takedown (max 31 Ultimate Haste)."},

    # Sorcery
    "8200": {"id": 8200, "name": "Sorcery", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/7202_Sorcery.png", "desc": "Unleash Destruction. Empowered abilities and resource manipulation."},
    "8214": {"id": 8214, "name": "Summon Aery", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/SummonAery/SummonAery.png", "desc": "Your attacks and abilities send Aery to damage enemies or shield allies."},
    "8229": {"id": 8229, "name": "Arcane Comet", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/ArcaneComet/ArcaneComet.png", "desc": "Damaging a champion with an ability hurls a damaging comet at their location."},
    "8230": {"id": 8230, "name": "Phase Rush", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/PhaseRush/PhaseRush.png", "desc": "Hitting an enemy champion with 3 separate attacks or spells grants a burst of Move Speed and 75% Slow Resist."},
    "8224": {"id": 8224, "name": "Nullifying Orb", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/NullifyingOrb/Pokeshield.png", "desc": "Gain a magic damage shield when taking magic damage that reduces you below 30% health."},
    "8226": {"id": 8226, "name": "Manaflow Band", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/ManaflowBand/ManaflowBand.png", "desc": "Hitting an enemy champion with an ability permanently increases your maximum mana by 25 (up to 250)."},
    "8275": {"id": 8275, "name": "Nimbus Cloak", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/NimbusCloak/6361.png", "desc": "After casting a Summoner Spell, gain a Move Speed increase and ghosting."},
    "8210": {"id": 8210, "name": "Transcendence", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/Transcendence/Transcendence.png", "desc": "Gain Ability Haste at levels 5 and 8. At level 11, takedowns reduce remaining basic ability cooldowns."},
    "8234": {"id": 8234, "name": "Celerity", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/Celerity/CelerityTemp.png", "desc": "All Move Speed bonuses are 7% more effective on you and gain +1% flat Move Speed."},
    "8233": {"id": 8233, "name": "Absolute Focus", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/AbsoluteFocus/AbsoluteFocus.png", "desc": "While above 70% health, gain bonus Adaptive Force."},
    "8237": {"id": 8237, "name": "Scorch", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/Scorch/Scorch.png", "desc": "Your next damaging ability sets champions on fire for bonus magic damage."},
    "8232": {"id": 8232, "name": "Waterwalking", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/Waterwalking/Waterwalking.png", "desc": "Gain Move Speed and bonus Adaptive Force while in the river."},
    "8236": {"id": 8236, "name": "Gathering Storm", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/GatheringStorm/GatheringStorm.png", "desc": "Gain increasing amounts of Adaptive Force every 10 minutes."},

    # Resolve
    "8400": {"id": 8400, "name": "Resolve", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/7204_Resolve.png", "desc": "Live Forever. Durability and crowd control resistance."},
    "8437": {"id": 8437, "name": "Grasp of the Undying", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/GraspOfTheUndying/GraspOfTheUndying.png", "desc": "Every 4s in combat, your next attack against a champion deals % max health, heals you, and permanently grants max Health."},
    "8439": {"id": 8439, "name": "Aftershock", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/VeteranAftershock/VeteranAftershock.png", "desc": "After immobilizing an enemy champion, gain massive Armor and Magic Resist, then detonate for magic damage."},
    "8465": {"id": 8465, "name": "Guardian", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/Guardian/Guardian.png", "desc": "Guard allies you are near. If either of you take damage, both receive a protective shield and speed."},
    "8446": {"id": 8446, "name": "Demolish", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/Demolish/Demolish.png", "desc": "Charge up a powerful strike against turrets when within 600 range, dealing massive damage based on max HP."},
    "8463": {"id": 8463, "name": "Font of Life", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/FontOfLife/FontOfLife.png", "desc": "Impairing the movement of an enemy champion heals you and nearby allies."},
    "8401": {"id": 8401, "name": "Shield Bash", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/MirrorShell/MirrorShell.png", "desc": "Whenever you gain a shield, gain bonus resistances and your next attack deals bonus adaptive damage."},
    "8429": {"id": 8429, "name": "Conditioning", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/Conditioning/Conditioning.png", "desc": "After 12 minutes, gain +8 Armor and +8 Magic Resist, and increase total resistances by 3%."},
    "8444": {"id": 8444, "name": "Second Wind", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/SecondWind/SecondWind.png", "desc": "After taking damage from an enemy champion, heal for 4% missing Health +6 over 10 seconds."},
    "8473": {"id": 8473, "name": "Bone Plating", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/BonePlating/BonePlating.png", "desc": "After taking damage from a champion, the next 3 attacks or spells deal 30-60 less damage."},
    "8451": {"id": 8451, "name": "Overgrowth", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/Overgrowth/Overgrowth.png", "desc": "Gain permanent max health when minions or monsters die near you. At 120 deaths, gain +3.5% max HP."},
    "8453": {"id": 8453, "name": "Revitalize", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Resolve/Revitalize/Revitalize.png", "desc": "Heals and shields you cast or receive are 5% stronger, increased to 10% on targets below 40% health."},
    "8242": {"id": 8242, "name": "Unflinching", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Sorcery/Unflinching/Unflinching.png", "desc": "Gain bonus Armor and Magic Resist while immobilized and for 2s after."},

    # Inspiration
    "8300": {"id": 8300, "name": "Inspiration", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/7203_Whimsy.png", "desc": "Creative Inventions. Rule-bending tools and match manipulation."},
    "8351": {"id": 8351, "name": "Glacial Augment", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/GlacialAugment/GlacialAugment.png", "desc": "Immobilizing an enemy shoots 3 glacial rays, creating frozen zones that slow enemies and reduce their damage by 15%."},
    "8360": {"id": 8360, "name": "Unsealed Spellbook", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/UnsealedSpellbook/UnsealedSpellbook.png", "desc": "Swap one of your equipped Summoner Spells to a new one while out of combat."},
    "8369": {"id": 8369, "name": "First Strike", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/FirstStrike/FirstStrike.png", "desc": "Attacking an enemy champion first grants 5g and +7% bonus damage for 3s, generating 100% of bonus damage as gold."},
    "8306": {"id": 8306, "name": "Hextech Flashtraption", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/HextechFlashtraption/HextechFlashtraption.png", "desc": "While Flash is on cooldown it is replaced by Hexflash (channel to blink to a new location)."},
    "8304": {"id": 8304, "name": "Magical Footwear", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/MagicalFootwear/MagicalFootwear.png", "desc": "Get free Slightly Magical Boots at 12 min (takedowns reduce timer by 45s), giving +10 extra Move Speed."},
    "8321": {"id": 8321, "name": "Cash Back", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/CashBack/CashBack.png", "desc": "Get 6% gold back when you purchase Legendary items."},
    "8313": {"id": 8313, "name": "Triple Tonic", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/TripleTonic/TripleTonic.png", "desc": "Gain special elixirs at levels 3 (gold), 6 (adaptive force), and 9 (free skill point)."},
    "8352": {"id": 8352, "name": "Time Warp Tonic", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/TimeWarpTonic/TimeWarpTonic.png", "desc": "Consuming potions grants immediate health/mana and +2% Move Speed."},
    "8345": {"id": 8345, "name": "Biscuit Delivery", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/BiscuitDelivery/BiscuitDelivery.png", "desc": "Get a free Total Biscuit of Everlasting Will every 2 min until 6 min. Restores health & permanently increases max mana."},
    "8347": {"id": 8347, "name": "Cosmic Insight", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/CosmicInsight/CosmicInsight.png", "desc": "+18 Summoner Spell Haste, +10 Item Haste."},
    "8410": {"id": 8410, "name": "Approach Velocity", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/ApproachVelocity/ApproachVelocity.png", "desc": "Gain +7.5% Move Speed towards movement-impaired allies or enemies you impair."},
    "8316": {"id": 8316, "name": "Jack of All Trades", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/Inspiration/JackOfAllTrades/JackofAllTrades.png", "desc": "For each different stat gained from items, gain +1 Ability Haste and Adaptive Force."},

    # Stat Shards
    "5008": {"id": 5008, "name": "Adaptive Force", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/StatMods/StatModsAdaptiveForceIcon.png", "desc": "+9 Adaptive Force (5.4 AD or 9 AP)."},
    "5005": {"id": 5005, "name": "Attack Speed", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/StatMods/StatModsAttackSpeedIcon.png", "desc": "+10% Attack Speed."},
    "5007": {"id": 5007, "name": "Ability Haste", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/StatMods/StatModsCDRScalingIcon.png", "desc": "+8 Ability Haste."},
    "5010": {"id": 5010, "name": "Movement Speed", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/StatMods/StatModsMovementSpeedIcon.png", "desc": "+2% Movement Speed."},
    "5001": {"id": 5001, "name": "Health Scaling", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/StatMods/StatModsHealthScalingIcon.png", "desc": "+10 to 180 Health (based on level)."},
    "5011": {"id": 5011, "name": "Flat Health", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/StatMods/StatModsHealthPlusIcon.png", "desc": "+65 Flat Health."},
    "5013": {"id": 5013, "name": "Tenacity", "icon": "https://ddragon.leagueoflegends.com/cdn/img/perk-images/StatMods/StatModsTenacityIcon.png", "desc": "+10% Tenacity and Slow Resist."}
}

SPELLS = {
    "Flash": {"id": "Flash", "name": "Flash", "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/spell/SummonerFlash.png", "cooldown": 300, "desc": "Teleports your champion a short distance toward your cursor's location."},
    "Teleport": {"id": "Teleport", "name": "Teleport", "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/spell/SummonerTeleport.png", "cooldown": 360, "desc": "After channeling for 4s, teleports your champion to target allied turret or structure."},
    "Ignite": {"id": "Ignite", "name": "Ignite", "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/spell/SummonerDot.png", "cooldown": 180, "desc": "Ignites target enemy champion, dealing 70-410 true damage over 5s and applying Grievous Wounds."},
    "Smite": {"id": "Smite", "name": "Smite", "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/spell/SummonerSmite.png", "cooldown": 90, "desc": "Deals 600-1200 true damage to target monster or minion."},
    "Heal": {"id": "Heal", "name": "Heal", "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/spell/SummonerHeal.png", "cooldown": 240, "desc": "Restores 80-318 Health and grants +30% Move Speed for 1s to you and target allied champion."},
    "Barrier": {"id": "Barrier", "name": "Barrier", "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/spell/SummonerBarrier.png", "cooldown": 180, "desc": "Shields your champion for 120-480 damage for 2.5 seconds."},
    "Exhaust": {"id": "Exhaust", "name": "Exhaust", "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/spell/SummonerExhaust.png", "cooldown": 210, "desc": "Slows enemy champion by 35% and reduces their damage dealt by 35% for 3 seconds."},
    "Cleanse": {"id": "Cleanse", "name": "Cleanse", "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/spell/SummonerBoost.png", "cooldown": 210, "desc": "Removes all disables (except suppression and airborne) and grants +65% Tenacity for 3 seconds."},
    "Ghost": {"id": "Ghost", "name": "Ghost", "image": "https://ddragon.leagueoflegends.com/cdn/14.23.1/img/spell/SummonerHaste.png", "cooldown": 240, "desc": "Gain +24-48% Move Speed and ghosting through units for 15 seconds."}
}

print("Basic items, runes and spells compiled successfully.")
